const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  category: {
    type: String,
    required: true,
  },
  // This stores the mathematical meaning of the product description generated by Gemini.
  embedding: {
    type: [Number],
    required: false,
  },
  stockQuantity: {
    type: Number,
    default: 100, // We will just pretend every item has 100 units in stock for now
  }
}, { timestamps: true });

const Product = mongoose.model('Product', productSchema);

module.exports = Product;
